name: Integration test CassandraSuite
on:
  pull_request:
    branches:
      - master
      - release-*

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  TestCassandraSuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        kubernetes-versions : ['v1.17.17', 'v1.22.0']
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: setup minikube
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: 'v1.22.0'
        kubernetes version: ${{ matrix.kubernetes-versions }}
        start args: --memory 6g --cpus=2
        github token: ${{ secrets.GITHUB_TOKEN }}

    - name: print k8s cluster status
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    - name: build rook
      run: |
        GOPATH=$(go env GOPATH) make clean && make -j$nproc IMAGES='cassandra' build
        docker images
        docker tag $(docker images|awk '/build-/ {print $1}') rook/cassandra:master

    - name: TestCassandraSuite
      run: |
        go test -v -timeout 1800s -run CassandraSuite github.com/rook/cassandra/tests/integration

    - name: Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cassandra-suite-artifact
        path: /home/runner/work/rook/cassandra/tests/integration/_output/tests/

    - name: setup tmate session for debugging
      if: failure()
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 60
