name: Integration test CephMgrSuite
on:
  pull_request:

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  TestCephMgrSuite:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-ci')"
    strategy:
      fail-fast: false
      matrix:
        kubernetes-versions : ['v1.22.0']
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: setup minikube
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: 'v1.22.0'
        kubernetes version: ${{ matrix.kubernetes-versions }}
        start args: --memory 6g --cpus=2
        github token: ${{ secrets.GITHUB_TOKEN }}

    - name: print k8s cluster status
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    - name: use local disk
      run: tests/scripts/github-action-helper.sh use_local_disk_for_integration_test

    - name: build rook
      run: tests/scripts/github-action-helper.sh build_rook

    - name: TestCephMgrSuite
      run: |
       export DEVICE_FILTER=$(lsblk|awk '/14G/ {print $1}'| head -1)
       go test -v -timeout 1800s -run CephMgrSuite github.com/rook/rook/tests/integration

    - name: Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ceph-mgr-suite-artifact
        path: /home/runner/work/rook/rook/tests/integration/_output/tests/

    - name: setup tmate session for debugging
      if: failure()
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 120
